services:
  goingrid-frontend:
    build:
      context: .
    container_name: goingrid-frontend
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - goingrid-proxy

networks:
  goingrid-proxy:
    external: true
    name: goingrid-proxy
