services:
  goingrid-frontend:
    build:
      context: .
      args:
        VITE_SUPABASE_URL: ${VITE_SUPABASE_URL}
        VITE_SUPABASE_ANON_KEY: ${VITE_SUPABASE_ANON_KEY}
    restart: unless-stopped
    networks:
      - goingrid-proxy

networks:
  goingrid-proxy:
    external: true
